run:
	docker compose -f compose.dev.yml up
restart:
	docker compose -f compose.dev.yml restart app
build-push:
	 docker build -t blessyo/hackathon-future-city:latest .
	 docker push blessyo/hackathon-future-city:latest